:toc: macro
= Hexboard UI

A hexboard for visualizing Kubernetes pod status

toc::[]

= Run the project on an OpenShift cluster

== Login to the cluster
[source, bash]
----
> oc login <openshift-cluster-ip>
> oc config view
----

Take note of the OAUTH token in the `config view` for your openshift cluster.

== Create the projects
[source, bash]
----
> oc new-project <project-name>
> oc new-app openshift/nodejs-010-centos7~http://github.com/bleathem/sketchpod
> oc new-app openshift/nodejs-010-centos7~http://github.com/bleathem/keynote2015-hexboard
> oc get builds -w
----

wait for the _sketchpod_ and _hexboard_ builds to complete

== Set the environment variables
[source, bash]
----
> oc env dc/keynote2015-hexboard ACCESS_TOKEN=<access-token>
> oc get pods -w
----

wait for the deployment to complete.

== Create the route to expose the service
[source, bash]
----
> oc expose service keynote2015-hexboard
> oc get route
----

this creates an external route for the service.  Make sure this route is addressable from wherever you are running your browser (an `/etc/hosts` entry in your client _may_ be required).

= Run the project locally (for UI development)

== Pre-requisutes:

* node.js (installed globally)
* gulp.js (installed globally)

== To install the project locally

Execute the following commands in your local clone of this repository:
[source, bash]
----
> npm install
----

== To run the project locally:

run `gulp` in it's own terminal:
[source, bash]
----
> PROXY="http://localhost:8080" OPENSHIFT_MASTER="localhost:8443" gulp
----

= Scaling the number of Pods
Animations of falling hexagons are triggered as the number of pods is scaled.
To scale the number of hexagons (either up or down) run the command:

[source, bash]
----
> oc scale dc/sketchpod --replicas=<number>
----

= Configuring the maximum number of Pods
The number of pods in the hexboard can be controlled by setting the `HEXBOARD_SIZE` environment variable:
[options="header"]
|===
| HEXBOARD_SIZE | # of pods |
| xsmall | 12 | _when running on a laptop_
| small | 108 | _minimum size when on ec2_
| medium | 266 |
| large _(default)_ | 513 |
| xlarge | 1,026 | _the "keynote" size_
|===

[source, bash]
----
> oc env dc/keynote2015-hexboard HEXBOARD_SIZE=<hexboard-size>
> oc get pods -w
----

NOTE: setting an environment variable triggers a new deployment, so watch the `oc get pods -w` output to see when the deployment is complete.
