= Location Force Layout

A location-scanner multi-foci force-layout built using d3.js and Rx.js.

The visualization itself is a client-side application.  However node.js and bower
are used to build the project and mange the dependencies respectively.

Pre-requisutes:

* node.js (installed globally)
* gulp.js (installed globally)
* bower (installed globally)

= To install the project

Execute the following commands in your local clone of this repository:
[source, bash]
----
> npm install
> bower install
----

= To run the project:

The project has 2 pieces:

* Beacon-location demo
** Mongo is required
* Thousand-container demo
** Mongo is optional

Note: Mongo is optional only on Node 0.10.  Node 0.12 will fail hard if it can't connect to mongo.

== Start mongo
Download mongod from the mongodb website, and place `mongod` on your path:
https://www.mongodb.org/

run `gulp mongo` in it's own terminal to start mongo (make sure no other instances of mongo are running)

== Start the project

run `gulp` in it's own terminal
