:toc: macro
= Hexboard UI

A hexboard for visualizing Kubernetes pod status

toc::[]

= Run the project on an OpenShift cluster

== Login to the cluster
[source, bash]
----
> oc login <openshift-cluster-ip>
> oc config view
----

Take note of the OAUTH token in the `config view` for your openshift cluster and include it as needed in example commands.

Export this configuration detail to use it in the following examples as `${ACCESS_TOKEN}`:

[source, bash]
----
> export ACCESS_TOKEN="YOUR_ACCESS_TOKEN_FROM_OC_CONFIG_VIEW"
----

== Create a project
Create a project to house this application:

[source, bash]
----
> oc new-project <project-name>
----

Load the project from a template:

[source, bash]
----
> oc create -f https://raw.githubusercontent.com/2015-Middleware-Keynote/hexboard/master/app_template.json
> oc process -v="HEXBOARD_HOST=${HEXBOARD_HOST},ACCESS_TOKEN=${ACCESS_TOKEN}" hexboard | oc create -f -
----

Or, create each service individually:

[source, bash]
----
> oc new-app openshift/nodejs-010-centos7~http://github.com/2015-Middleware-Keynote/sketchpod
> oc new-app openshift/nodejs-010-centos7~http://github.com/2015-Middleware-Keynote/hexboard
----

Then, check the results:

[source, bash]
----
> oc get builds -w
----

wait for the _sketchpod_ and _hexboard_ builds to complete.  Or, start the builds as needed:

[source, bash]
----
> oc start-build hexboard
> oc start-build sketchpod
----

Watch the progress:

[source, bash]
----
> oc get pods -w
----

= Expose the Hexboard Service with a Route
The optional `--hostname` flag allows you to create custom routes:

[source, bash]
----
> oc expose service hexboard --hostname=<hexboard-host-url>
> oc get route
----

this creates an external route for the service.  Make sure this route is addressable from wherever you are running your browser (an `/etc/hosts` entry in your client _may_ be required).

To run this service in a VM, try exposing the hexboard service at `localhost`, while setting your `HEXBOARD_HOST` config to `localhost:1080`.

== Configure with environment variables

These configs can also be set while loading a project from a template via the web console, or via the `oc process` command.  

To reconfigure a running hexboard service, run the following to share your `oc` cli tool's current oauth token:

[source, bash]
----
> oc env dc/hexboard ACCESS_TOKEN="${ACCESS_TOKEN}"
----

Update your proxy host URL info.  This example issues the `oc get route` command to use any routes that you've established in previous steps.

[source, bash]
----
> export HEXBOARD_HOST=$(oc get routes -o template -t '''{{with index .items 0}}{{.spec.host}}{{end}}''')
> oc env dc/hexboard HEXBOARD_HOST="${HEXBOARD_HOST}"
----

The number of pods in the hexboard can be controlled by setting the `HEXBOARD_SIZE` environment variable:
[options="header"]
|===
| HEXBOARD_SIZE | # of pods |
| xsmall | 12 | _when running on a laptop_
| small | 108 | _minimum size when on ec2_
| medium | 266 |
| large _(default)_ | 513 |
| xlarge | 1,026 | _the "keynote" size_
|===

[source, bash]
----
> oc env dc/hexboard HEXBOARD_SIZE=<hexboard-size>
> oc get pods -w
----

NOTE: setting an environment variable triggers a new deployment, so watch the `oc get pods -w` output to see when the deployment is complete.

= Scaling the number of Pods
Animations of falling hexagons are triggered as the number of pods is scaled.
To scale the number of hexagons (either up or down) run the command:

[source, bash]
----
> oc scale rc/sketchpod --replicas=<number>
----

= Run the hexboard locally (for UI development)

== Pre-requisutes:

* node.js (installed globally)
* gulp.js (installed globally)

== To install the project locally

Execute the following commands in your local clone of this repository:
[source, bash]
----
> npm install
----

== To run the hexboard locally:

run `gulp` in it's own terminal:
[source, bash]
----
> PORT=8081 HEXBOARD_HOST="localhost:8081" ACCESS_TOKEN="${ACCESS_TOKEN}" OPENSHIFT_SERVER="localhost:8443" NAMESPACE=hexboard gulp
----
