:toc: macro
= Hexboard UI

Container vizualization for link:http://openshift.com/[OpenShift platformV3]. As featured in the link:https://www.youtube.com/watch?v=wWNVpFibayA&t=26m48s[Red Hat Summit 2015 - JBoss Keynote demo]

toc::[]

= Basic Setup

To use a VM, follow the setup instructions from link:http://bit.ly/v3devs[this workshop]

== Authentication
[source, bash]
----
oc login <openshift-cluster-ip>
oc config view
----

Take note of the OAUTH token in the `config view` for your openshift cluster and include it as needed in example commands.

Export this configuration detail to use it in the following examples as `${ACCESS_TOKEN}`:

[source, bash]
----
export ACCESS_TOKEN="YOUR_ACCESS_TOKEN_FROM_OC_CONFIG_VIEW"
----

== Create a project
Create a project to house this application:

[source, bash]
----
oc new-project <project-name>
----

Install and launch the project from a template:

[source, bash]
----
oc create -f https://raw.githubusercontent.com/2015-Middleware-Keynote/hexboard/master/app_template.json
oc process -v="ACCESS_TOKEN=${ACCESS_TOKEN}" hexboard | oc create -f -
----

Or, create each service individually:

[source, bash]
----
oc new-app openshift/nodejs-010-centos7~http://github.com/2015-Middleware-Keynote/sketchpod
oc new-app -e "ACCESS_TOKEN=${ACCESS_TOKEN}" openshift/nodejs-010-centos7~http://github.com/2015-Middleware-Keynote/hexboard
----

Then, check the results:

[source, bash]
----
oc get builds -w
----

= Builds

Docker image builds can be initiated by navigating to the "Builds" tab in the V3 web console. Click on the **Start Build** button for each service.

You can also initiate the builds from the command line:

[source, bash]
----
oc start-build hexboard
oc start-build sketchpod
----

Watch the progress:

[source, bash]
----
oc get pods -w
----

= Routing

In order to view the hexboard, you'll need to expose your service by setting up a Route.
The optional `--hostname` flag allows you to create a custom route to an existing `service`:

[source, bash]
----
oc expose se/hexboard --hostname=<your-hexboard-hostname>
----

This creates an external route for the service.  Make sure this route is addressable from wherever you are running your browser (an `/etc/hosts` entry in your client _may_ be required).

Excluding the `--hostname` flag should generate a default route that automatically takes advantage of your cluster's wildcard DNS (if available):

[source, bash]
----
oc expose se/hexboard
----

Now, try listing your existing routes:

[source, bash]
----
oc get route
----

= Configuration

The service configuration is provided via environment variables. These configs can be set while loading a project from a template via the web console or via the `oc process` command.  

You can also add environment keys to an existing deployment config using the `oc env` command.  Setting new configuration details will trigger a deployment to distribute your changes (if needed).

To set the **required** `ACCESS_TOKEN` config, follow the instructions in the above link:#authentication[Authentication] section, using your own `ACCESS_TOKEN` value in the following example:

[source, bash]
----
oc env dc/hexboard ACCESS_TOKEN="${ACCESS_TOKEN}"
----

The number of pods in the hexboard can be controlled by setting the `HEXBOARD_SIZE` environment variable:
[options="header"]
|===
| HEXBOARD_SIZE | # of pods |
| xsmall | 12 | _when running on a laptop_
| small | 108 | _minimum size when on ec2_
| medium | 266 |
| large _(default)_ | 513 |
| xlarge | 1,026 | _the "keynote" size_
|===

[source, bash]
----
oc env dc/hexboard HEXBOARD_SIZE=<hexboard-size>
oc get pods -w
----

NOTE: setting an environment variable triggers a new deployment, so watch the `oc get pods -w` output to see when the deployment is complete.

= Scaling
Animations of falling hexagons are triggered as the number of pods is scaled.
To scale the number of hexagons (either up or down) run the command:

[source, bash]
----
oc scale rc/sketchpod-1 --replicas=<number>
----

After scaling up, try submitting sketches by visiting the hexboard's bundled mobile web submission form, at `http://your-hexboard-hostname/mobile/`.

= Local Development

== Pre-Requisutes

* node.js (installed globally)
* gulp.js (installed globally)

== Installation

Execute the following commands in your local clone of this repository:
[source, bash]
----
npm install
----

== Run the hexboard locally

Run `gulp` in it's own terminal, providing environment variables that reference an available OpenShift cluster where your `sketchpod` service back-ends will be hosted and scaled:

[source, bash]
----
PORT=8081 PROXY="localhost:1080" ACCESS_TOKEN="${ACCESS_TOKEN}" OPENSHIFT_SERVER="localhost:8443" NAMESPACE=hexboard gulp
----

= Cleanup

You can clear out everything in your existing project by running the following:

[source, bash]
----
oc delete all --all
----

TIP: Be careful to verify that you're logged into the correct server and project before running this command!
